// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.twerno.eduserver.user.entities;


privileged aspect Grupa_Roo_JavaBean {
    
    public String Grupa.getNazwa() {
        return this.nazwa;
    }
    
    public void Grupa.setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    
}
