// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.twerno.eduserver.user.domain;

import net.twerno.eduserver.user.domain.AccountDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AccountIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AccountIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AccountIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: AccountIntegrationTest: @Transactional;
    
    @Autowired
    private AccountDataOnDemand AccountIntegrationTest.dod;
    
    @Test
    public void AccountIntegrationTest.testCountAccounts() {
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", dod.getRandomAccount());
        long count = net.twerno.eduserver.user.domain.Account.countAccounts();
        org.junit.Assert.assertTrue("Counter for 'Account' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AccountIntegrationTest.testFindAccount() {
        net.twerno.eduserver.user.domain.Account obj = dod.getRandomAccount();
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to provide an identifier", id);
        obj = net.twerno.eduserver.user.domain.Account.findAccount(id);
        org.junit.Assert.assertNotNull("Find method for 'Account' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Account' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AccountIntegrationTest.testFindAllAccounts() {
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", dod.getRandomAccount());
        long count = net.twerno.eduserver.user.domain.Account.countAccounts();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Account', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<net.twerno.eduserver.user.domain.Account> result = net.twerno.eduserver.user.domain.Account.findAllAccounts();
        org.junit.Assert.assertNotNull("Find all method for 'Account' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Account' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AccountIntegrationTest.testFindAccountEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", dod.getRandomAccount());
        long count = net.twerno.eduserver.user.domain.Account.countAccounts();
        if (count > 20) count = 20;
        java.util.List<net.twerno.eduserver.user.domain.Account> result = net.twerno.eduserver.user.domain.Account.findAccountEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Account' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Account' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AccountIntegrationTest.testFlush() {
        net.twerno.eduserver.user.domain.Account obj = dod.getRandomAccount();
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to provide an identifier", id);
        obj = net.twerno.eduserver.user.domain.Account.findAccount(id);
        org.junit.Assert.assertNotNull("Find method for 'Account' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAccount(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Account' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AccountIntegrationTest.testMerge() {
        net.twerno.eduserver.user.domain.Account obj = dod.getRandomAccount();
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to provide an identifier", id);
        obj = net.twerno.eduserver.user.domain.Account.findAccount(id);
        boolean modified =  dod.modifyAccount(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        net.twerno.eduserver.user.domain.Account merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Account' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AccountIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", dod.getRandomAccount());
        net.twerno.eduserver.user.domain.Account obj = dod.getNewTransientAccount(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Account' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Account' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AccountIntegrationTest.testRemove() {
        net.twerno.eduserver.user.domain.Account obj = dod.getRandomAccount();
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Account' failed to provide an identifier", id);
        obj = net.twerno.eduserver.user.domain.Account.findAccount(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Account' with identifier '" + id + "'", net.twerno.eduserver.user.domain.Account.findAccount(id));
    }
    
}
